######################################################################
# Automatically generated by qmake (1.07a) Tue Apr 12 21:55:14 2005
######################################################################

TEMPLATE = lib
TARGET = carofe
VERSION = 0.1.0
DESTDIR = ../plugins/
INCLUDEPATH += .
CONFIG+= qt thread opengl warn_off dll
# Input
HEADERS += modelsviewplugin.h mvglwidget.h carofeplugin.h ascview.h asc.h
SOURCES += mvglwidget.cpp carofeplugin.cpp ascview.cpp asc.cpp
